server:
  port: 8083

spring:
  application:
    name: ACTIVITYSERVICE

  data:
    mongodb:
      uri: mongodb+srv://morwanisujal875:Test12345@cluster0.tcirwh4.mongodb.net/vectorDB?retryWrites=true&w=majority
      database: vectorDB

  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text
        enabled: true

    vectorstore:
      mongodb:
        collection-name: embeddings
        initialize-schema: true
        enabled: true

  kafka:
    bootstrap-servers: 172.26.50.52:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



kafka:
  topic:
    name: activity-events


