server:
  port: 8085

spring:
  application:
    name: AISERVICE

  data:
    mongodb:
      uri: mongodb+srv://morwanisujal875:Test12345@cluster0.tcirwh4.mongodb.net/airecommendationfitness?retryWrites=true&w=majority
      database: airecommendationfitness

  kafka:
    bootstrap-servers: 172.26.50.52:9092
    consumer:
      group-id: debug-single-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      listener:
        concurrency: 1
      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

kafka:
  topic:
    name: activity-events


logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka.clients.consumer: DEBUG


gemini:
  api:
    url: {GEMINI_URL}
    key: {GEMINI_KEY}